version: '3.8'
services:
  gazebo-web:
    build:
      context: .
      dockerfile: GazeboWeb
    image: gazebo-web-image:latest
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - ./:/workspace:rw
    command: "/root/start_gzserver.sh"
    ports:
      - "8080:8080"
