version: '3.8'
services:
  ros-humble:
    build:
      context: .
      dockerfile: ROSHumblegz.Dockerfile
    image: ros-humble-gz:latest
    environment:
      - DISPLAY=${DISPLAY}
      - QT_X11_NO_MITSHM=1
    volumes:
      - "/tmp/.X11-unix:/tmp/.X11-unix:rw"
      - ./:/workspace:rw
    devices:
      - /dev/dri:/dev/dri
    group_add:
      - video
    command: sleep infinity
    ports:
      - "8080:8080"
    working_dir: /workspace
